### ISSUE TITLE
go get complains about local imports

### ISSUE THREAD

**Issue by wbl** [mchackorg/gonts#6]
$go get -v github.com/mchackorg/gonts/...
../../../golang/src/github.com/mchackorg/gonts/client/client.go:9:2: local import "../ntske" in non-local package
../../../golang/src/github.com/mchackorg/gonts/ntskeserver/main.go:9:2: local import "../ntske" in non-local package

**Comment by quite** [comment]
Yeah the project is very bare-bones in its setup :) It builds locally if you clone it and my PR #5 helps building all binaries, dropping them in `build/`

**Comment by wbl** [comment]
I did clone it into my GOPATH and it still complained! What do you do to build this?

**Comment by mchackorg** [comment]
Now uses go.mod (#8) and a makefile but a simple go get github.com/mchackorg/gonts/cmd/... should work.
